### ISSUE TITLE
preprocessing script refers to data in survey folder (rather than data)

### ISSUE THREAD

**Issue by ekothe** [jlbeaudry/incoming_students#3]
Should be 

```
# raw data without labels
df_num <- here::here("data", "students_raw_data.csv") %>%
  read_qualtrics(legacy = TRUE) %>%
  mutate(id = 1:n())


# raw data with labels
df_lab <- here::here("data", "students_raw_data_with_labels.csv") %>%
  read_qualtrics(legacy = FALSE) %>%
  mutate(id = 1:n())
```

**Comment by jlbeaudry** [comment]
According to Dani's [template](https://github.com/djnavarro/newproject/tree/master/experiments/exp_urntask/data), the raw data should be in the "experiments/data" folder, which is why I put it under "survey/data". The data in the main "data folder" is the processed data that's ready for analysis. 

I like her template, so I'd like to leave it as is. Okay with you?

**Comment by ekothe** [comment]
Absolutely! I didn't realise that there was also a data folder in survey (it's wisely in the gitignore) so I was having build errors. Happy to stay with the templated structure.
